---
Name: site-wide-search
---
SilverStripe\Core\Injector\Injector:
  Psr\SimpleCache\CacheInterface.siteWideSearch:
    factory: SilverStripe\Core\Cache\CacheFactory
    constructor:
      namespace: 'siteWideSearch'
      defaultLifetime: 864000

SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - 'sunnysideup/site-wide-search: client/dist/styles/search.css'
  extra_requirements_javascript:
    - 'sunnysideup/site-wide-search: client/dist/js/search.js'
